version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: backend_c
    ports:
      - '3000:3000'
    volumes:
      - ./backend/app:/app
      - /app/node_modules

  frontend:
    build: 
      context: ./frontend
    container_name: frontend_c
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
